/*
 * This is the Card Gui JForm class which Introduce Cards in the GUI application
 */
package GUI;

import javax.swing.JPanel;
import uk.ac.tees.cis2001.pocketbeasts.BeastCard;

/**
 *
 * @author JATIN ANEJA
 */
public class Card_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Card_GUI
     */
    public Card_GUI(BeastCard card) {
        initComponents();
        ManaCost.setText(Integer.toString(card.getManaCost()));
        CardName.setText(card.getId());
        Attack.setText(Integer.toString(card.getAttack()));
        Health.setText(Integer.toString(card.getHealth()));
        CardPanel.validate();
        CardPanel.repaint();
    }
    public void setCoordinates(int x, int y){
        this.CardPanel.setBounds(x, y, 110, 135);
    }
    public JPanel getCardPanel(){
        return this.CardPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CardPanel = new javax.swing.JPanel();
        ManaCost = new javax.swing.JLabel();
        CardName = new javax.swing.JLabel();
        Attack = new javax.swing.JLabel();
        Health = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CardPanel.setBackground(new java.awt.Color(204, 203, 243));
        CardPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        ManaCost.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ManaCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManaCost.setText("  M");
        ManaCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CardName.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        CardName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CardName.setText(" Name");
        CardName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Attack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Attack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Attack.setText("  A");
        Attack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Health.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Health.setText("   H");
        Health.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout CardPanelLayout = new javax.swing.GroupLayout(CardPanel);
        CardPanel.setLayout(CardPanelLayout);
        CardPanelLayout.setHorizontalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardPanelLayout.createSequentialGroup()
                .addComponent(Attack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Health, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(CardName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(CardPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ManaCost, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CardPanelLayout.setVerticalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPanelLayout.createSequentialGroup()
                .addComponent(ManaCost, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(CardName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Attack, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(Health, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Attack;
    private javax.swing.JLabel CardName;
    public static javax.swing.JPanel CardPanel;
    private javax.swing.JLabel Health;
    private javax.swing.JLabel ManaCost;
    // End of variables declaration//GEN-END:variables
}
