/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JPanel;
import uk.ac.tees.cis2001.pocketbeasts.MagicCard;

/**
 *
 * @author JATIN ANEJA
 */
public class SpellCards_GUI extends javax.swing.JFrame {

    /**
     * Creates new form SpellCards_GUI
     */
    public SpellCards_GUI(MagicCard card) {
        initComponents();
        SpellMana.setText(Integer.toString(card.getManaCost()));
        CardType.setText(card.getName());
        SpellEffect.setText(card.getId());
        
        spellCardPanel.validate();
        spellCardPanel.repaint();
    }
    public void setCoordinates(int x, int y){
        this.spellCardPanel.setBounds(x, y, 110, 135);
    }
    public JPanel getCardPanel(){
        return this.spellCardPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spellCardPanel = new javax.swing.JPanel();
        CardType = new javax.swing.JLabel();
        SpellEffect = new javax.swing.JLabel();
        SpellMana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        spellCardPanel.setBackground(new java.awt.Color(255, 255, 153));
        spellCardPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        CardType.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        CardType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CardType.setText(" Name");
        CardType.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        SpellEffect.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SpellEffect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SpellEffect.setText(" E");
        SpellEffect.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SpellMana.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SpellMana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SpellMana.setText("  M");
        SpellMana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout spellCardPanelLayout = new javax.swing.GroupLayout(spellCardPanel);
        spellCardPanel.setLayout(spellCardPanelLayout);
        spellCardPanelLayout.setHorizontalGroup(
            spellCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CardType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(spellCardPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(SpellEffect, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spellCardPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SpellMana, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        spellCardPanelLayout.setVerticalGroup(
            spellCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spellCardPanelLayout.createSequentialGroup()
                .addComponent(SpellMana, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(CardType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SpellEffect, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spellCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spellCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CardType;
    private javax.swing.JLabel SpellEffect;
    private javax.swing.JLabel SpellMana;
    private javax.swing.JPanel spellCardPanel;
    // End of variables declaration//GEN-END:variables
}
